forEach: Model
fileName: openapi.yaml
ifDuplicated: merge
except: true
---
{{#boundedContexts}}
{{#if aggregates}}
{{#aggregates}}
{{#if commands}}
{{#commands}}
{{#if isRestRepository}}
{{else}}
paths:
  /{{#aggregate}}{{namePlural}}{{/aggregate}}/{id}{{#checkMethod controllerInfo}}{{/checkMethod}}:
    summary: {{name}} operation on {{#aggregate}}{{namePlural}}{{/aggregate}}
    {{controllerInfo.method}}:
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
              {{#fieldDescriptors}}
                {{name}}:
                  description: {{name}} of this {{../namePascalCase}}
                  type: {{#changeType className}}{{/changeType}}
              {{/fieldDescriptors}}
            {{#if examples}}
            examples:
            {{#examples}}
              Example {{@index}}:   
              {{#when}}
                value:
                {{#each value}}
                  {{@key}}: {{this}}
                {{/each}}
              {{/when}}
            {{/examples}}      
            {{/if}}
      parameters:
      - name: id
        description: {{namePascalCase}} name
        schema:
          type: {{#changeType aggregate.aggregateRoot.keyFieldDescriptor.className}}{{/changeType}}
        in: path
        required: true
        examples:
        {{#if examples}}
          {{#examples}}
          Example {{@index}}:   
            {{#when}}
            value:
              {{#each value}}
              {{@key}}: {{this}}
            {{/each}}
          {{/when}}
        {{/examples}}
        {{/if}}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{aggregate.namePascalCase}}'
              examples:
              {{#if examples}}
              {{#examples}}
                Example {{@index}}: 
              {{#then}}
                  value:
                  {{#each value}}
                    {{@key}}: {{this}}
                  {{/each}}
              {{/then}}
              {{/examples}}
              {{/if}}
          description: {{namePascalCase}} Operation
      operationId: {{namePascalCase}}
      summary: {{namePascalCase}}
      description: {{namePascalCase}}
{{/if}}
{{/commands}}
{{/if}}
{{/aggregates}}
{{/if}}
{{/boundedContexts}}

<function>

  window.$HandleBars.registerHelper('checkMethod', function (command) {
    if(command.method == 'POST'){
      return command.apiPath;
    }else{
      return '/' + command.apiPath;
    }
  })

  window.$HandleBars.registerHelper('changeType', function (type) {
    if (type === 'Double' || type === 'double' || type === 'BigDecimal' || type === 'float') {
      return 'number';
    }
    if (type === 'Integer' || type === 'integer' || type === 'Long' || type === 'long') {
      return 'integer';
    }
    if (type === 'String') {
      return 'string';
    }
    return 'string';
  })

</function>