forEach: Model
fileName: openapi.yaml
ifDuplicated: merge
---
{{#boundedContexts}}
{{#if aggregates}}
{{#aggregates}}
{{#if commands}}
{{#commands}}
{{if isRestRepository}}
{{else}}
paths:
  /{{#aggregate}}{{namePlural}}{{/aggregate}}/{id}{{#if (controllerInfo.method 'POST')}}{{controllerInfo.apiPath}}{{else}}/{{controllerInfo.apiPath}}{{/if}}:
    summary: {{name}} operation on {{#aggregate}}{{namePlural}}{{/aggregate}}
    {{controllerInfo.method}}:
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
              {{#fieldDescriptors}}
                {{name}}:
                  description: {{name}} of this {{../namePascalCase}}
                  type: {{map @root.contexts.mappings className}}
              {{/fieldDescriptors}}
            {{#if examples}}
            examples:
            {{#examples}}
              Example {{@index}}:   
            {{#when}}
                value:
                {{#each value}}
                  {{@key}}: {{this}}
                {{/each}}
            {{/when}}
            {{/examples}}      
      parameters:
      - name: id
        description: {{namePascalCase}} name
        schema:
          type: {{map @root.contexts.mappings aggregate.aggregateRoot.keyFieldDescriptor.className}}
        in: path
        required: true
        examples:
        {{#if examples}}
          {{#examples}}
          Example {{@index}}:   
            {{#when}}
            value:
              {{#each value}}
              {{@key}}: {{this}}
            {{/each}}
          {{/when}}
        {{/examples}}
        {{/if}}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{aggregate.namePascalCase}}'
              examples:
              {{#examples}}
                Example {{@index}}: 
              {{#then}}
                  value:
                  {{#each value}}
                    {{@key}}: {{this}}
                  {{/each}}
              {{/then}}
              {{/examples}}      
              {{^examples}}
                1:
                  value:
                  {{#aggregate.aggregateRoot.fieldDescriptors}}
                    {{name}}: {{map @root.contexts.examples className}}
                  {{/aggregate.aggregateRoot.fieldDescriptors}}
              {{/examples}}
          description: {{namePascalCase}} Operation
      operationId: {{namePascalCase}}
      summary: {{namePascalCase}}
      description: {{namePascalCase}}
{{/if}}
{{/commands}}
{{/if}}
{{/aggregates}}
{{/if}}
{{/boundedContexts}}

<function>
    
    this.contexts.command = this.target

    this.contexts.mappings = [
      {
        "if":['Double', 'double', 'BigDecimal', 'float'],
        "then":'number'
      },
      {
        "if":['Integer', 'integer', 'Long', 'long'],
        "then": 'integer'
      },
      {
        "if":['String'],
        "then": 'string'
      },
      {
        "default": 'string'
      }
    ]

    this.contexts.examples = [
      {
        "if":['Double', 'double', 'BigDecimal', 'float'],
        "then":1.1
      },
      {
        "if":['Integer', 'integer', 'Long', 'long'],
        "then": 1
      },
      {
        "if":['String'],
        "then": 'A string'
      },
      {
        "default": 'value'
      }
    ]

</function>